import type { QuasarIconSet } from "quasar"

export const CUSTOM_QUASAR_ICON_SET: QuasarIconSet = {
  name: "icons",
  type: {
    positive: "check_circle",
    negative: "warning",
    info: "info",
    warning: "priority_high",
  },
  arrow: {
    up: "arrow_upward",
    right: "arrow_forward",
    down: "arrow_downward",
    left: "arrow_back",
    dropdown: "arrow_downward",
  },
  chevron: {
    left: "chevron_left",
    right: "chevron_right",
  },
  colorPicker: {
    spectrum: "gradient",
    tune: "tune",
    palette: "style",
  },
  pullToRefresh: {
    icon: "refresh",
  },
  carousel: {
    left: "chevron_left",
    right: "chevron_right",
    up: "keyboard_arrow_up",
    down: "keyboard_arrow_down",
    navigationIcon: "lens",
  },
  chip: {
    remove: "cancel",
    selected: "check",
  },
  datetime: {
    arrowLeft: "chevron_left",
    arrowRight: "chevron_right",
    now: "access_time",
    today: "today",
  },
  editor: {
    bold: "format_bold",
    italic: "format_italic",
    strikethrough: "strikethrough_s",
    underline: "format_underlined",
    unorderedList: "format_list_bulleted",
    orderedList: "format_list_numbered",
    subscript: "vertical_align_bottom",
    superscript: "vertical_align_top",
    hyperlink: "link",
    toggleFullscreen: "fullscreen",
    quote: "format_quote",
    left: "format_align_left",
    center: "format_align_center",
    right: "format_align_right",
    justify: "format_align_justify",
    print: "print",
    outdent: "format_indent_decrease",
    indent: "format_indent_increase",
    removeFormat: "format_clear",
    formatting: "text_format",
    fontSize: "format_size",
    align: "format_align_left",
    hr: "remove",
    undo: "undo",
    redo: "redo",
    heading: "format_size",
    heading1: "format_size",
    heading2: "format_size",
    heading3: "format_size",
    heading4: "format_size",
    heading5: "format_size",
    heading6: "format_size",
    code: "code",
    size: "format_size",
    size1: "format_size",
    size2: "format_size",
    size3: "format_size",
    size4: "format_size",
    size5: "format_size",
    size6: "format_size",
    size7: "format_size",
    font: "font_download",
    viewSource: "code",
  },
  expansionItem: {
    icon: "keyboard_arrow_down",
    denseIcon: "arrow_drop_down",
  },
  fab: {
    icon: "add",
    activeIcon: "close",
  },
  field: {
    clear: "cancel",
    error: "error",
  },
  pagination: {
    first: "first_page",
    prev: "keyboard_arrow_left",
    next: "keyboard_arrow_right",
    last: "last_page",
  },
  rating: {
    icon: "grade",
  },
  stepper: {
    done: "check",
    active: "edit",
    error: "warning",
  },
  tabs: {
    left: "chevron_left",
    right: "chevron_right",
    up: "keyboard_arrow_up",
    down: "keyboard_arrow_down",
  },
  table: {
    arrowUp: "arrow_upward",
    warning: "warning",
    firstPage: "first_page",
    prevPage: "chevron_left",
    nextPage: "chevron_right",
    lastPage: "last_page",
  },
  tree: {
    icon: "play_arrow",
  },
  uploader: {
    done: "done",
    clear: "clear",
    add: "add_box",
    upload: "cloud_upload",
    removeQueue: "clear_all",
    removeUploaded: "done_all",
  },
};
